language: node_js
node_js:
    - 13

services:
    - docker

install:
    - echo "nothing needs to be installed"

before_script:
    - echo "no tests"

script:
    - docker --version
    - docker build -t dinhdangkhoa0201/udagram-api-user .
#    - docker tag udagram-api-user dinhdangkhoa0201/udagram-api-user

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push dinhdangkhoa0201/udagram-api-user
